import { useEffect, useMemo, useState } from 'react';
import { Archive, ArrowLeft, ArrowRight, Copy, FolderOpen, ImagePlus, LogIn, LogOut, Plus, RefreshCw, RotateCcw, Save, Search, Star, Trash2, X } from 'lucide-react';
import { deleteProduct, isCurrentUserAdmin, loadAdminProducts, loadOrders, saveProduct, signInAdmin, signOutAdmin, updateOrderStatus, uploadProductImages } from './store';
import { clearProductPhotos, deleteProductPhoto, saveProductGallery, setProductActive } from './adminCatalog';
import { supabaseConfigured } from './supabase';
import type { OrderRow, Product, ProductVariant } from './types';
import BulkPhotoPanel from './BulkPhotoPanel';

const newVariant=(productId:string,baseSku=''):ProductVariant=>({id:crypto.randomUUID(),product_id:productId,sku:baseSku?`${baseSku}-S-NGR`:'' ,size:'S',color:'Negro',stock:0,active:true});
const fresh=():Product=>{const id=crypto.randomUUID();return{id,sku:'',name:'',category:'Mujer',collection:'Workout',price:0,old_price:null,description:'',sizes:['S'],colors:['Negro'],stock:0,badge:null,image:'',images:[],color_images:{},active:true,sort_order:999,variants:[newVariant(id)]}};

export default function AdminPanel({open,onClose,onCatalogChanged}:{open:boolean;onClose:()=>void;onCatalogChanged:()=>void}){
 const [ok,setOk]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[products,setProducts]=useState<Product[]>([]),[orders,setOrders]=useState<OrderRow[]>([]),[editing,setEditing]=useState<Product|null>(null),[msg,setMsg]=useState(''),[uploading,setUploading]=useState(false),[bulkOpen,setBulkOpen]=useState(false),[query,setQuery]=useState(''),[categoryFilter,setCategoryFilter]=useState('Todos'),[statusFilter,setStatusFilter]=useState('Activos'),[page,setPage]=useState(1);
 const pageSize=12;
 const totalVariantStock=useMemo(()=>editing?.variants?.filter(v=>v.active).reduce((s,v)=>s+Number(v.stock||0),0)||0,[editing]);
 const refresh=async()=>{setProducts(await loadAdminProducts());setOrders(await loadOrders())};
 useEffect(()=>{if(open&&supabaseConfigured)isCurrentUserAdmin().then(v=>{setOk(v);if(v)refresh()})},[open]);
 useEffect(()=>setPage(1),[query,categoryFilter,statusFilter]);
 const filtered=useMemo(()=>products.filter(p=>{
  const matchesQuery=!query.trim()||`${p.name} ${p.sku} ${p.collection}`.toLowerCase().includes(query.toLowerCase());
  const matchesCategory=categoryFilter==='Todos'||p.category===categoryFilter;
  const matchesStatus=statusFilter==='Todos'||(statusFilter==='Activos'?p.active:!p.active);
  return matchesQuery&&matchesCategory&&matchesStatus;
 }),[products,query,categoryFilter,statusFilter]);
 const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize));
 const visible=filtered.slice((page-1)*pageSize,page*pageSize);
 if(!open)return null;
 const login=async()=>{try{await signInAdmin(email,password);setOk(true);await refresh()}catch(e:any){setMsg(e.message)}};
 const persist=async()=>{if(!editing)return;try{await saveProduct(editing);setEditing(null);setMsg('Producto guardado correctamente.');await refresh();onCatalogChanged()}catch(e:any){setMsg(e.message)}};
 const upload=async(files:FileList|null)=>{if(!editing||!files?.length)return;setUploading(true);try{const urls=await uploadProductImages(editing.id,Array.from(files));setEditing({...editing,images:[...editing.images,...urls],image:editing.image||urls[0]||''});setMsg(`${urls.length} fotos procesadas y subidas.`)}catch(e:any){setMsg(e.message)}finally{setUploading(false)}};
 const patchVariant=(id:string,patch:Partial<ProductVariant>)=>setEditing(p=>p?({...p,variants:(p.variants||[]).map(v=>v.id===id?{...v,...patch}:v)}):p);
 const addVariant=()=>setEditing(p=>p?({...p,variants:[...(p.variants||[]),newVariant(p.id,p.sku)]}):p);
 const cloneVariant=(v:ProductVariant)=>setEditing(p=>p?({...p,variants:[...(p.variants||[]),{...v,id:crypto.randomUUID(),sku:`${v.sku}-2`}]}):p);
 const removeVariant=(id:string)=>setEditing(p=>p?({...p,variants:(p.variants||[]).filter(v=>v.id!==id)}):p);
 const duplicateProduct=(p:Product)=>{const id=crypto.randomUUID();setEditing({...p,id,sku:`${p.sku}-COPIA`,name:`${p.name} copia`,active:false,images:[],image:'',color_images:{},variants:(p.variants||[]).map(v=>({...v,id:crypto.randomUUID(),product_id:id,sku:`${v.sku}-C`}))})};
 const movePhoto=async(index:number,delta:number)=>{if(!editing)return;const target=index+delta;if(target<0||target>=editing.images.length)return;const images=[...editing.images];[images[index],images[target]]=[images[target],images[index]];const next={...editing,images};setEditing(next);await saveProductGallery(next)};
 const removePhoto=async(url:string)=>{if(!editing)return;if(!confirm('¿Eliminar esta foto del producto?'))return;try{const next=await deleteProductPhoto(editing,url);setEditing(next);setMsg('Foto eliminada.')}catch(e:any){setMsg(e.message)}};
 const clearPhotos=async()=>{if(!editing||!editing.images.length)return;if(!confirm('¿Eliminar TODAS las fotos de este producto?'))return;try{const next=await clearProductPhotos(editing);setEditing(next);setMsg('Galería vaciada.')}catch(e:any){setMsg(e.message)}};
 const makePrimary=async(url:string)=>{if(!editing)return;const next={...editing,image:url};setEditing(next);try{await saveProductGallery(next);setMsg('Foto principal actualizada.')}catch(e:any){setMsg(e.message)}};
 return <div className="fixed inset-0 z-[90] overflow-y-auto bg-black/70 p-4"><div className="mx-auto min-h-[80vh] max-w-7xl bg-[#f4f2ed]"><div className="flex items-center justify-between border-b p-5"><div><p className="text-xs font-black uppercase tracking-[.2em] text-black/40">Mateo’s</p><h2 className="font-display text-4xl">PANEL ADMINISTRADOR</h2></div><button onClick={onClose}><X/></button></div>{!supabaseConfigured?<div className="p-8">Supabase pendiente.</div>:!ok?<div className="mx-auto max-w-md p-8"><h3 className="font-display text-4xl">INICIAR SESIÓN</h3><input className="field mt-5" placeholder="Correo admin" value={email} onChange={e=>setEmail(e.target.value)}/><input className="field mt-3" type="password" placeholder="Contraseña" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={login} className="mt-4 flex w-full items-center justify-center gap-2 bg-black px-5 py-4 font-black uppercase text-white"><LogIn/> Entrar</button>{msg&&<p className="mt-4 text-sm text-red-700">{msg}</p>}</div>:<div className="p-5 lg:p-8"><div className="mb-6 flex flex-wrap gap-3"><button onClick={()=>setEditing(fresh())} className="flex items-center gap-2 bg-black px-4 py-3 text-sm font-black uppercase text-white"><Plus/> Nuevo producto</button><button onClick={()=>setBulkOpen(true)} className="flex items-center gap-2 border border-black bg-white px-4 py-3 text-sm font-black uppercase"><FolderOpen/> Carga masiva de fotos</button><button onClick={refresh} className="flex items-center gap-2 border border-black px-4 py-3 text-sm font-black uppercase"><RefreshCw/> Actualizar</button><button onClick={async()=>{await signOutAdmin();setOk(false)}} className="ml-auto flex items-center gap-2 border border-black px-4 py-3 text-sm font-black uppercase"><LogOut/> Salir</button></div>{msg&&<p className="mb-5 bg-white p-3 text-sm font-bold">{msg}</p>}
 <div className="mb-5 grid gap-3 md:grid-cols-[1fr_180px_180px]"><label className="flex items-center gap-2 bg-white px-3"><Search size={18}/><input className="w-full bg-transparent py-3 outline-none" placeholder="Buscar por nombre, SKU o colección" value={query} onChange={e=>setQuery(e.target.value)}/></label><select className="field" value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option>Todos</option><option>Mujer</option><option>Hombre</option><option>Niños</option></select><select className="field" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option>Activos</option><option>Archivados</option><option>Todos</option></select></div>
 <div className="grid gap-8 lg:grid-cols-[1.25fr_.75fr]"><section><div className="flex items-end justify-between"><div><h3 className="font-display text-3xl">PRODUCTOS ({filtered.length})</h3><p className="text-xs text-black/50">Activos {products.filter(p=>p.active).length} · Archivados {products.filter(p=>!p.active).length}</p></div><p className="text-xs font-bold">Página {page}/{totalPages}</p></div><div className="mt-4 space-y-3">{visible.map(p=><div key={p.id} className={`grid grid-cols-[70px_1fr_auto] items-center gap-3 p-3 ${p.active?'bg-white':'bg-black/5 opacity-70'}`}><img src={p.image||p.images[0]||'https://placehold.co/140x160?text=Sin+foto'} className="h-20 w-[70px] object-cover"/><button className="text-left" onClick={()=>setEditing({...p,variants:p.variants||[]})}><div className="flex items-center gap-2"><b>{p.name}</b><span className={`px-2 py-0.5 text-[10px] font-black uppercase ${p.active?'bg-[#c9ff36]':'bg-black text-white'}`}>{p.active?'Publicado':'Archivado'}</span></div><p className="text-xs text-black/50">{p.sku} · {p.category} · {p.variants?.length||0} variantes · Stock {p.stock}</p><p className="text-sm font-black">S/ {p.price.toFixed(2)}</p></button><div className="flex flex-col gap-2"><button title="Duplicar" onClick={()=>duplicateProduct(p)} className="border p-2"><Copy size={17}/></button>{p.active?<button title="Archivar" onClick={async()=>{if(!confirm('¿Archivar este producto?'))return;await setProductActive(p.id,false);await refresh();onCatalogChanged()}} className="border p-2"><Archive size={17}/></button>:<button title="Restaurar" onClick={async()=>{await setProductActive(p.id,true);await refresh();onCatalogChanged()}} className="border p-2"><RotateCcw size={17}/></button>}</div></div>)}{!visible.length&&<div className="bg-white p-8 text-center text-sm text-black/50">No hay productos con esos filtros.</div>}</div><div className="mt-4 flex justify-between"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)} className="border px-4 py-2 font-bold disabled:opacity-30">Anterior</button><button disabled={page>=totalPages} onClick={()=>setPage(p=>p+1)} className="border px-4 py-2 font-bold disabled:opacity-30">Siguiente</button></div></section><section><h3 className="font-display text-3xl">PEDIDOS ({orders.length})</h3><div className="mt-4 space-y-3">{orders.map(o=><div key={o.id} className="bg-white p-4"><div className="flex justify-between gap-3"><div><b>{o.code}</b><p className="text-xs text-black/50">{o.customer_name} · {o.phone}</p></div><b>S/ {Number(o.total).toFixed(2)}</b></div><select className="field mt-3" value={o.status} onChange={async e=>{await updateOrderStatus(o.id,e.target.value);await refresh()}}><option>Nuevo</option><option>Confirmado</option><option>En preparación</option><option>Enviado</option><option>Entregado</option><option>Cancelado</option></select></div>)}</div></section></div></div>}
 {editing&&<div className="fixed inset-0 z-[100] overflow-y-auto bg-black/70 p-4"><div className="mx-auto my-8 max-w-5xl bg-[#f4f2ed] p-6"><div className="flex justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-black/40">Registro de inventario</p><h3 className="font-display text-4xl">{editing.name||'NUEVO PRODUCTO'}</h3><p className="mt-1 text-xs font-bold uppercase text-black/50">{editing.active?'Publicado':'Archivado'}</p></div><button onClick={()=>setEditing(null)}><X/></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><input className="field" placeholder="SKU base (ej. LEG-001)" value={editing.sku} onChange={e=>setEditing({...editing,sku:e.target.value.toUpperCase()})}/><input className="field lg:col-span-2" placeholder="Nombre del producto" value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/><select className="field" value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value as Product['category']})}><option>Mujer</option><option>Hombre</option><option>Niños</option></select><input className="field" placeholder="Colección" value={editing.collection} onChange={e=>setEditing({...editing,collection:e.target.value})}/><input className="field" placeholder="Etiqueta (Nuevo, Oferta...)" value={editing.badge||''} onChange={e=>setEditing({...editing,badge:e.target.value||null})}/><input className="field" type="number" step="0.1" placeholder="Precio" value={editing.price} onChange={e=>setEditing({...editing,price:Number(e.target.value)})}/><input className="field" type="number" step="0.1" placeholder="Precio anterior" value={editing.old_price||''} onChange={e=>setEditing({...editing,old_price:e.target.value?Number(e.target.value):null})}/><div className="field bg-white font-black">Stock total automático: {totalVariantStock}</div><textarea className="field sm:col-span-2 lg:col-span-3" placeholder="Descripción" value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})}/><label className="sm:col-span-2 lg:col-span-3 flex cursor-pointer items-center justify-center gap-2 border-2 border-dashed border-black/30 bg-white p-6 font-black uppercase"><ImagePlus/> {uploading?'Procesando fotos...':'Seleccionar varias fotos'}<input type="file" accept="image/*" multiple className="hidden" onChange={e=>upload(e.target.files)}/></label>
 {editing.images.length>0&&<div className="sm:col-span-2 lg:col-span-3"><div className="mb-3 flex items-center justify-between"><div><b>Galería ({editing.images.length})</b><p className="text-xs text-black/50">La estrella indica la foto principal.</p></div><button onClick={clearPhotos} className="flex items-center gap-2 border border-red-700 px-3 py-2 text-xs font-black uppercase text-red-700"><Trash2 size={15}/> Quitar todas</button></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5">{editing.images.map((u,i)=><div key={`${u}-${i}`} className={`relative bg-white p-2 ${editing.image===u?'ring-2 ring-black':''}`}><div className="relative aspect-square overflow-hidden bg-black/5"><img src={u} className="h-full w-full object-cover"/>{editing.image===u&&<span className="absolute left-2 top-2 flex items-center gap-1 bg-[#c9ff36] px-2 py-1 text-[10px] font-black uppercase"><Star size={12}/> Principal</span>}</div><div className="mt-2 grid grid-cols-4 gap-1"><button title="Principal" onClick={()=>makePrimary(u)} className="border p-2"><Star size={14}/></button><button title="Mover izquierda" onClick={()=>movePhoto(i,-1)} disabled={i===0} className="border p-2 disabled:opacity-25"><ArrowLeft size={14}/></button><button title="Mover derecha" onClick={()=>movePhoto(i,1)} disabled={i===editing.images.length-1} className="border p-2 disabled:opacity-25"><ArrowRight size={14}/></button><button title="Eliminar foto" onClick={()=>removePhoto(u)} className="border border-red-700 p-2 text-red-700"><Trash2 size={14}/></button></div></div>)}</div></div>}</div>
 <div className="mt-8"><div className="flex items-center justify-between gap-3"><div><h4 className="font-display text-3xl">VARIANTES</h4><p className="text-sm text-black/55">Una fila por combinación real de talla y color.</p></div><button onClick={addVariant} className="flex items-center gap-2 border border-black bg-white px-4 py-3 text-sm font-black uppercase"><Plus size={18}/> Agregar variante</button></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] border-collapse bg-white text-sm"><thead><tr className="border-b text-left text-xs uppercase tracking-wide text-black/50"><th className="p-3">SKU variante</th><th className="p-3">Talla</th><th className="p-3">Color</th><th className="p-3">Stock</th><th className="p-3">Activa</th><th className="p-3">Acciones</th></tr></thead><tbody>{(editing.variants||[]).map(v=><tr key={v.id} className="border-b last:border-0"><td className="p-2"><input className="field" value={v.sku} onChange={e=>patchVariant(v.id,{sku:e.target.value.toUpperCase()})}/></td><td className="p-2"><input className="field" value={v.size} onChange={e=>patchVariant(v.id,{size:e.target.value})}/></td><td className="p-2"><input className="field" value={v.color} onChange={e=>patchVariant(v.id,{color:e.target.value})}/></td><td className="p-2"><input className="field" type="number" min="0" value={v.stock} onChange={e=>patchVariant(v.id,{stock:Number(e.target.value)})}/></td><td className="p-2 text-center"><input type="checkbox" checked={v.active} onChange={e=>patchVariant(v.id,{active:e.target.checked})}/></td><td className="p-2"><div className="flex gap-2"><button title="Duplicar" onClick={()=>cloneVariant(v)} className="border p-2"><Copy size={16}/></button><button title="Eliminar" onClick={()=>removeVariant(v.id)} className="border p-2"><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><button onClick={async()=>{await setProductActive(editing.id,!editing.active);setEditing({...editing,active:!editing.active});await refresh();onCatalogChanged()}} className="flex items-center justify-center gap-2 border border-black px-5 py-4 font-black uppercase">{editing.active?<><Archive/> Archivar producto</>:<><RotateCcw/> Restaurar producto</>}</button><button onClick={persist} className="flex items-center justify-center gap-2 bg-black px-5 py-4 font-black uppercase text-white"><Save/> Guardar producto</button></div></div></div>}
 <BulkPhotoPanel open={bulkOpen} onClose={()=>setBulkOpen(false)} products={products} onComplete={async()=>{await refresh();onCatalogChanged();}}/>
 </div></div>;
}
