import type { Product } from './types';

export const fallbackCatalog: Product[] = [
  { id:'M-001', sku:'M-001', name:'Set Power Flex Black', category:'Mujer', collection:'Workout', price:89.9, old_price:109.9, image:'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=900&q=82', images:[], sizes:['S','M','L'], colors:['Negro','Olivo'], stock:12, badge:'Nuevo', active:true, sort_order:10, description:'Conjunto workout de ajuste cómodo, cintura alta y tejido flexible para entrenamiento o uso diario.' },
  { id:'M-002', sku:'M-002', name:'Legging Motion Mocha', category:'Mujer', collection:'Workout', price:59.9, image:'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=900&q=82', images:[], sizes:['S','M','L','XL'], colors:['Mocha','Negro'], stock:18, badge:'Tendencia', active:true, sort_order:20, description:'Legging de tiro alto con tacto suave y soporte medio. Ideal para gimnasio y looks urbanos.' },
  { id:'M-003', sku:'M-003', name:'Oversize Urban Sand', category:'Mujer', collection:'Confort', price:54.9, image:'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=900&q=82', images:[], sizes:['S/M','L/XL'], colors:['Arena','Blanco'], stock:10, active:true, sort_order:30, description:'Polo oversize de caída relajada, algodón suave y estilo minimalista para combinar con biker o jogger.' },
  { id:'M-004', sku:'M-004', name:'Biker Active Cobalt', category:'Mujer', collection:'Workout', price:49.9, image:'https://images.unsplash.com/photo-1534258936925-c58bed479fcb?auto=format&fit=crop&w=900&q=82', images:[], sizes:['S','M','L'], colors:['Cobalto','Negro'], stock:14, active:true, sort_order:40, description:'Biker deportivo de cintura alta, elástico y fresco para rutinas intensas o uso casual.' },
  { id:'H-001', sku:'H-001', name:'Set Performance Carbon', category:'Hombre', collection:'Workout', price:99.9, old_price:119.9, image:'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?auto=format&fit=crop&w=900&q=82', images:[], sizes:['S','M','L','XL'], colors:['Carbono','Negro'], stock:15, badge:'Más vendido', active:true, sort_order:50, description:'Set deportivo de polo y short con secado rápido, diseño limpio y libertad de movimiento.' },
  { id:'H-002', sku:'H-002', name:'Jogger Comfort Black', category:'Hombre', collection:'Confort', price:69.9, image:'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=900&q=82', images:[], sizes:['S','M','L','XL'], colors:['Negro','Gris'], stock:16, active:true, sort_order:60, description:'Jogger de corte moderno con puños, bolsillos laterales y felpa ligera para todo el día.' },
  { id:'H-003', sku:'H-003', name:'Polo Dry Motion White', category:'Hombre', collection:'Deportivo', price:44.9, image:'https://images.unsplash.com/photo-1526401485004-2aa7c19c0c6b?auto=format&fit=crop&w=900&q=82', images:[], sizes:['S','M','L','XL'], colors:['Blanco','Negro','Azul'], stock:22, active:true, sort_order:70, description:'Polo deportivo ligero, respirable y de secado rápido para entrenamiento y actividades diarias.' },
  { id:'H-004', sku:'H-004', name:'Cortaviento Street Navy', category:'Hombre', collection:'Urbano', price:84.9, image:'https://images.unsplash.com/photo-1550345332-09e3ac987658?auto=format&fit=crop&w=900&q=82', images:[], sizes:['M','L','XL'], colors:['Navy','Negro'], stock:9, badge:'Edición urbana', active:true, sort_order:80, description:'Casaca cortaviento liviana con silueta urbana y protección ideal para tardes frías.' },
  { id:'N-001', sku:'N-001', name:'Buzo Mini Move Sky', category:'Niños', collection:'Confort', price:74.9, image:'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=900&q=82', images:[], sizes:['4','6','8','10','12'], colors:['Celeste','Gris'], stock:11, badge:'Nuevo', active:true, sort_order:90, description:'Buzo cómodo y resistente para jugar, estudiar o salir, con acabado suave al tacto.' },
  { id:'N-002', sku:'N-002', name:'Set Play Active Green', category:'Niños', collection:'Deportivo', price:69.9, image:'https://images.unsplash.com/photo-1514090458221-65bb69cf63e6?auto=format&fit=crop&w=900&q=82', images:[], sizes:['4','6','8','10'], colors:['Verde','Azul'], stock:13, active:true, sort_order:100, description:'Conjunto de polo y short para movimiento libre, juegos y actividades deportivas.' },
  { id:'N-003', sku:'N-003', name:'Polo Kids Motion', category:'Niños', collection:'Urbano', price:34.9, image:'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=900&q=82', images:[], sizes:['4','6','8','10','12'], colors:['Blanco','Negro','Naranja'], stock:20, active:true, sort_order:110, description:'Polo de algodón con diseño urbano, cómodo y fácil de combinar para el uso diario.' },
  { id:'N-004', sku:'N-004', name:'Jogger Junior Grey', category:'Niños', collection:'Confort', price:49.9, image:'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&w=900&q=82', images:[], sizes:['6','8','10','12','14'], colors:['Gris','Negro'], stock:17, active:true, sort_order:120, description:'Jogger junior de tejido suave, cintura regulable y bolsillos funcionales.' }
];
