import { fallbackCatalog } from './fallbackCatalog';
import { supabase, supabaseConfigured } from './supabase';
import type { CartItem, CheckoutForm, OrderRow, Product } from './types';

const normalize = (row: any): Product => ({ id:String(row.id), sku:String(row.sku||row.id), name:String(row.name), category:row.category, collection:String(row.collection||'General'), price:Number(row.price), old_price:row.old_price==null?null:Number(row.old_price), description:String(row.description||''), sizes:Array.isArray(row.sizes)?row.sizes:[], colors:Array.isArray(row.colors)?row.colors:[], stock:Number(row.stock||0), badge:row.badge||null, image:String(row.image||row.images?.[0]||''), images:Array.isArray(row.images)?row.images:[], active:row.active!==false, sort_order:Number(row.sort_order||0) });

export async function loadPublicProducts(): Promise<Product[]> { if(!supabaseConfigured||!supabase) return fallbackCatalog; const {data,error}=await supabase.from('products').select('*').eq('active',true).order('sort_order',{ascending:true}); if(error||!data?.length) return fallbackCatalog; return data.map(normalize); }
export async function createOrder(form:CheckoutForm,items:CartItem[],total:number){ const code=`MAT-${new Date().toISOString().slice(2,10).replaceAll('-','')}-${crypto.randomUUID().slice(0,6).toUpperCase()}`; if(!supabaseConfigured||!supabase)return code; const id=crypto.randomUUID(); const destination=`${form.department}, ${form.province}, ${form.district}`; const {error}=await supabase.from('orders').insert({id,code,customer_name:form.name.trim(),phone:form.phone.trim(),destination,department:form.department,province:form.province.trim(),district:form.district.trim(),shipping_method:form.shipping,agency:form.agency||null,notes:form.notes||null,total,status:'Nuevo'}); if(error)throw error; const {error:itemError}=await supabase.from('order_items').insert(items.map(item=>({order_id:id,product_id:item.id,product_name:item.name,sku:item.sku,size:item.size,color:item.color,quantity:item.quantity,unit_price:item.price,line_total:item.price*item.quantity}))); if(itemError)throw itemError; return code; }
export async function signInAdmin(email:string,password:string){ if(!supabase)throw new Error('Supabase todavía no está configurado.'); const {data,error}=await supabase.auth.signInWithPassword({email,password}); if(error)throw error; const userId=data.user?.id; if(!userId)throw new Error('No se pudo validar la cuenta.'); const {data:admin,error:adminError}=await supabase.from('store_admins').select('user_id').eq('user_id',userId).maybeSingle(); if(adminError||!admin){await supabase.auth.signOut();throw new Error('Esta cuenta no tiene permisos de administrador.')} return data.user; }
export async function isCurrentUserAdmin(){ if(!supabase)return false; const {data:userData}=await supabase.auth.getUser(); if(!userData.user)return false; const {data}=await supabase.from('store_admins').select('user_id').eq('user_id',userData.user.id).maybeSingle(); return Boolean(data); }
export async function signOutAdmin(){ if(supabase)await supabase.auth.signOut(); }
export async function loadAdminProducts():Promise<Product[]>{ if(!supabase)return[]; const {data,error}=await supabase.from('products').select('*').order('sort_order'); if(error)throw error; return(data||[]).map(normalize); }
export async function saveProduct(product:Product){ if(!supabase)throw new Error('Supabase no configurado.'); const {error}=await supabase.from('products').upsert({...product,old_price:product.old_price||null,badge:product.badge||null},{onConflict:'id'}); if(error)throw error; }
export async function deleteProduct(id:string){ if(!supabase)throw new Error('Supabase no configurado.'); const {error}=await supabase.from('products').update({active:false}).eq('id',id); if(error)throw error; }
export async function loadOrders():Promise<OrderRow[]>{ if(!supabase)return[]; const {data,error}=await supabase.from('orders').select('id,code,customer_name,phone,destination,shipping_method,agency,total,status,created_at').order('created_at',{ascending:false}).limit(100); if(error)throw error; return(data||[]) as OrderRow[]; }
export async function updateOrderStatus(id:string,status:string){ if(!supabase)return; const {error}=await supabase.from('orders').update({status}).eq('id',id); if(error)throw error; }
async function compressImage(file:File):Promise<Blob>{ const bitmap=await createImageBitmap(file); const max=1800; const scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height)); const canvas=document.createElement('canvas'); canvas.width=Math.round(bitmap.width*scale); canvas.height=Math.round(bitmap.height*scale); canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height); const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('No se pudo comprimir la imagen.')),'image/webp',0.84)); bitmap.close(); return blob; }
export async function uploadProductImages(productId:string,files:File[]):Promise<string[]>{ if(!supabase)throw new Error('Supabase no configurado.'); const urls:string[]=[]; for(const file of files){ if(!file.type.startsWith('image/'))continue; const blob=await compressImage(file); const path=`${productId}/${Date.now()}-${crypto.randomUUID()}.webp`; const {error}=await supabase.storage.from('product-images').upload(path,blob,{contentType:'image/webp',cacheControl:'31536000',upsert:false}); if(error)throw error; const {data}=supabase.storage.from('product-images').getPublicUrl(path); urls.push(data.publicUrl); } return urls; }
